### ISSUE TITLE
Estimar espaço de armazenamento necessário

### ISSUE THREAD

**Issue by AndreaInfUFSM** [dmoreiras/Projeto-II-Debora-e-Michele#7]
Calcular espaço de armazenamento para cada ave na planilha, incluindo texto, imagem e som (tamanho médio de arquivos), para estimar a quantidade máxima de aves na planilha que não cause degradação no desempenho.

**Comment by MicheleGiane9** [comment]
Segue no link o máximo de dados que podem conter uma planilha do excel .Entretanto seu desempenho poderia ficar afetado com muitas informações .Acho que  online poderia armazenar umas 100 e umas 50 aves local, porém ficaria um pouco lento.
https://support.office.com/pt-br/article/Especifica%C3%A7%C3%B5es-e-limites-do-Microsoft-Excel-1672b34d-7043-467e-8e27-269d656771c3
